language: generic
sudo: false

notifications:
  webhooks:
    urls:
      - https://canary.discordapp.com/api/webhooks/270231302177816576/mi-FyqrlSB42RdEG26MEp8kK0GXwzyzQBwmy4xePxmpdreMQP_riqAjLNlSCZfp7v5TE
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1423"
    - DM_BUILDFILE="cev_eris.dme"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh 
  - ./install-byond.sh

script:
  - (! grep 'step_[xy]' maps/*.dmm)
  - (! grep -E "(/obj/machinery/door/firedoor).*\1" maps/*.dmm)
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
#  - bash dm.sh -M${DM_MAPFILE} ${DM_BUILDFILE}
  - bash dm.sh ${DM_BUILDFILE}
